---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metronomikon-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metronomikon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metronomikon-cluster-role
subjects:
- kind: ServiceAccount
  name: metronomikon
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metronomikon
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metronomikon
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metronomikon
  template:
    metadata:
      labels:
        app: metronomikon
    spec:
      serviceAccountName: metronomikon
      containers:
      - name: metronomikon
        image: applause/metronomikon:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metronomikon
  namespace: kube-system
spec:
  selector:
    app: metronomikon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
