apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
  - name: http-9090
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app: metronomikon
