---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metronomikon
  namespace: metronomikon-test
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: metronomikon
          servicePort: 8080
