replicaCount: 1

image:
  repository: applause/metronomikon
  pullPolicy: IfNotPresent
  tag: "1.1.0"

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80
  annotations: {}
  externalTrafficPolicy: Local

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    memory: "128Mi"
